# Generated by Django 4.2.26 on 2025-11-13 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appKairos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultado',
            options={'ordering': ['anio', 'fecha'], 'verbose_name': 'Resultado', 'verbose_name_plural': 'Resultados'},
        ),
        migrations.RenameField(
            model_name='resultado',
            old_name='capital',
            new_name='capital_mes',
        ),
        migrations.RenameField(
            model_name='tokenverificacionemail',
            old_name='fecha_expiracion',
            new_name='expira_en',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='doble_autenticacion_activa',
            new_name='tiene_2fa_activo',
        ),
        migrations.AlterUniqueTogether(
            name='resultado',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productocontratado',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='sesionseguridad',
            name='email_intento',
        ),
        migrations.AddField(
            model_name='productocontratado',
            name='capital_actual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Capital actual en euros', max_digits=12),
        ),
        migrations.AddField(
            model_name='productocontratado',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productocontratado',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resultado',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha del resultado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='secreto_2fa',
            field=models.CharField(blank=True, help_text='Secreto para generar códigos TOTP', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='productocontratado',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('cancelado', 'Cancelado'), ('pendiente', 'Pendiente')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='productocontratado',
            name='monto_invertido',
            field=models.DecimalField(decimal_places=2, help_text='Monto invertido inicial en euros', max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='resultado',
            unique_together={('usuario', 'producto_contratado', 'fecha')},
        ),
    ]
