# Generated by Django 4.2.26 on 2025-11-15 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appKairos', '0002_alter_resultado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRecuperacionPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Token de Recuperación de Contraseña',
                'verbose_name_plural': 'Tokens de Recuperación de Contraseña',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigos_respaldo_2fa',
            field=models.TextField(blank=True, help_text='Códigos de respaldo encriptados para 2FA (separados por comas)', null=True),
        ),
        migrations.AlterField(
            model_name='sesionseguridad',
            name='fecha_intento',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(db_index=True, help_text='Email del usuario (usado para login)', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AddIndex(
            model_name='productocontratado',
            index=models.Index(fields=['usuario', 'estado'], name='appKairos_p_usuario_27b382_idx'),
        ),
        migrations.AddIndex(
            model_name='productocontratado',
            index=models.Index(fields=['fecha_contratacion'], name='appKairos_p_fecha_c_ca47e5_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionseguridad',
            index=models.Index(fields=['-fecha_intento'], name='appKairos_s_fecha_i_cba207_idx'),
        ),
        migrations.AddField(
            model_name='tokenrecuperacionpassword',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
